services:
  - type: web
    name: fixofy
    runtime: node
    buildCommand: npm run build --legacy-peer-deps
    startCommand: npm start
    envVars:
      - key: USE_SUPABASE
        value: "true"
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SERVICE_KEY
        sync: false
      - key: VITE_GOOGLE_MAPS_API_KEY
        sync: false
      - key: VITE_SUPABASE_URL
        sync: false
      - key: VITE_SUPABASE_ANON_KEY
        sync: false
      - key: NODE_VERSION
        value: "18.x"
